server:
  port: 8888

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/MicroservicePhanHoangPhuc/Config_server.git
          default-label: master
        bootstrap: false